stages:
  - test
  - production

cache:
  key: ${CI_COMMIT_REF_NAME}
  paths:
    - node_modules

prod-build:
  stage: production
  tags:
    - vue-h5-runner
  only:
    - tags
  script:
    - cnpm install --progress=false
    - npm run build
  artifacts:
    # 使用当前stage和分支名称作为存档名称
    name: '${CI_PROJECT_NAME}_${CI_COMMIT_TAG}'
    # 工件缓存的有效时间
    expire_in: 3 days
    # 路径
    paths:
      - www

test-build:
  stage: test
  tags:
    - vue-h5-runner
  only:
    - test
  script:
    - cnpm install --progress=false
    - npm run test
  artifacts:
    # 使用当前stage和分支名称作为存档名称
    name: '${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}'
    # 工件缓存的有效时间
    expire_in: 3 days
    # 路径
    paths:
      - www
